name: Deploy Flask app 

on:
    workflow_dispatch:

jobs:
    deploy:
    runs-on: self-hosted

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

          name: deploy with docker and build 
          uses: 