name: hello

on:
  workflow_dispatch: 
  # We are only pushing when in these file path , files got changed
  # push:
  #   branches: [main]
  #   paths:
  #     - '**.html'
  #     - '**.yml'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to user
        run: echo "Hello Dosto !!"

      - name: say hello to user name 
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: version of python , docker
        run: docker --version && python --version
        
